### PR TITLE
EncApp: Add support for HDR10+ JSON file

### PR DESCRIPTION
**Pull request by quietvoid**
Requires new C API lib from https://github.com/quietvoid/hdr10plus_tool/tree/main/hdr10plus
Lazy approach where the JSON is parsed and returned as a handle. And payload is generated for every frame.

### CODE REVIEW

**Review by gianni-rosato — APPROVED** [review]
LGTM. Myself or someone else will document the new parameter, you don't have to add documentation. Thanks again

**Comment by juliobbv-p** [comment]
Nice job, works perfectly! I've just encoded my first HDR10+ video in AV1.

pizza-hdr10plus

**Comment by quietvoid** [comment]
No, ask MediaInfo to support it.

**Comment by Patman86** [comment]
hmmm, info before encode:

image

info after encode:

image

**Comment by Patman86** [comment]
> No, ask MediaInfo if it supports this. FFmpeg already does, you can try using `ffprobe`.

Mediainfo can handle this.
Info before encoding:

image

Info after encoding:

image

**Comment by quietvoid** [comment]
That's an HEVC file.

**Comment by Patman86** [comment]
@quietvoid i've tested ffprobe for a while now, but ffprobe hasn't shown me any detailed info that HDR10+ content is included. Can you help here?

**Comment by quietvoid** [comment]
It only shows the frame metadata with `ffprobe -show_frames`
```
[SIDE_DATA]
side_data_type=HDR Dynamic Metadata SMPTE2094-40 (HDR10+)
```

**Comment by gianni-rosato** [comment]
@Patman86 In the future, I would ask that you please deal with issues you are having with SVT-AV1-PSY by opening an issue in our GitHub repo so we can address your issue more quickly and keep track of progress. Thanks so much.

**Comment by Patman86** [comment]
I apologise, I will comply with this in future. In this case, however, it was not directly a problem with SVT-AV1-PSY, but rather checking the function of the corresponding library. Here quietvoid was able to help me quite quickly as the author of the library. Thank you for implementing the library!

**Pull request merged**
